language: node_js
os: linux
sudo: required
dist: trusty
addons:
  apt:
    packages:
    - libxi-dev
    - mesa-utils
    - xvfb
    - libgl1-mesa-dri
    - libglapi-mesa
    - libosmesa6
node_js:
  - '8'
before_install:
  - npm install gl-matrix@3.0.0
before_script:
  - export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start
